# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/ol/Sourcecode/azpr led/hw/project/vivado2020/vivado2020.cache/wt} [current_project]
set_property parent.project_path {D:/ol/Sourcecode/azpr led/hw/project/vivado2020/vivado2020.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/ol/Sourcecode/azpr led/hw/project/vivado2020/vivado2020.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/include/nettype.h}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/include/stddef.h}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/include/global_config.h}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/include/cpu.h}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/bus/include/bus.h}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/io/rom/include/rom.h}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/io/timer/include/timer.h}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/io/gpio/include/gpio.h}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/io/uart/include/uart.h}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/include/isa.h}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/include/spm.h}
}
set_property file_type "Verilog Header" [get_files {{D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/include/nettype.h}}]
set_property file_type "Verilog Header" [get_files {{D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/include/stddef.h}}]
set_property file_type "Verilog Header" [get_files {{D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/include/global_config.h}}]
set_property file_type "Verilog Header" [get_files {{D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/include/cpu.h}}]
set_property file_type "Verilog Header" [get_files {{D:/ol/Sourcecode/azpr led/hw/rtl_sea/bus/include/bus.h}}]
set_property file_type "Verilog Header" [get_files {{D:/ol/Sourcecode/azpr led/hw/rtl_sea/io/rom/include/rom.h}}]
set_property file_type "Verilog Header" [get_files {{D:/ol/Sourcecode/azpr led/hw/rtl_sea/io/timer/include/timer.h}}]
set_property file_type "Verilog Header" [get_files {{D:/ol/Sourcecode/azpr led/hw/rtl_sea/io/gpio/include/gpio.h}}]
set_property file_type "Verilog Header" [get_files {{D:/ol/Sourcecode/azpr led/hw/rtl_sea/io/uart/include/uart.h}}]
set_property file_type "Verilog Header" [get_files {{D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/include/isa.h}}]
set_property file_type "Verilog Header" [get_files {{D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/include/spm.h}}]
read_mem {{D:/ol/Sourcecode/azpr led/sw/Sample_Program_SEA/1.LED/test_binary.dat}}
read_verilog -library xil_defaultlib {
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/alu.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/bus/rtl/bus.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/bus/rtl/bus_addr_dec.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/bus/rtl/bus_arbiter.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/bus_if.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/bus/rtl/bus_master_mux.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/bus/rtl/bus_slave_mux.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/rtl/chip.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/rtl/clk_gen.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/cpu.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/ctrl.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/decoder.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/ex_reg.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/ex_stage.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/io/gpio/rtl/gpio.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/gpr.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/id_reg.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/id_stage.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/if_reg.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/if_stage.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/mem_ctrl.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/mem_reg.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/mem_stage.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/io/rom/rtl/rom.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/cpu/rtl/spm.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/io/timer/rtl/timer.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/lib/x_s3e_dcm.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/lib/x_s3e_dpram.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/lib/x_s3e_sprom.v}
  {D:/ol/Sourcecode/azpr led/hw/rtl_sea/top/rtl/chip_top.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/ol/Sourcecode/azpr led/hw/constraint/system.xdc}}
set_property used_in_implementation false [get_files {{D:/ol/Sourcecode/azpr led/hw/constraint/system.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top chip_top -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef chip_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file chip_top_utilization_synth.rpt -pb chip_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
